# Banco de dados (Supabase)
spring.datasource.url=jdbc:postgresql://db.oozejrhduovqgngtjqcx.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# Email
# Email (Resend)
spring.mail.host=smtp.resend.com
spring.mail.port=465
spring.mail.username=resend
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true

# RabbitMQ (CloudAMQP)
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=5671
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.virtual-host=${RABBITMQ_USERNAME}
spring.rabbitmq.ssl.enabled=true

# Filas
rabbitmq.queue.email-transacao=fila.email.transacao
rabbitmq.queue.email-resgate=fila.email.resgate

server.port=8080